# Generated by Django 2.1.4 on 2019-01-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20181228_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.TextField()),
                ('c2', models.TextField()),
                ('c3', models.TextField()),
                ('c4', models.TextField()),
                ('c5', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='publickeys',
            name='secret_keys',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
